version: '3'
services:
  web:
    image: ${NGINX_IMAGE}
    ports:
      - "80:80"
    volumes:
      - ${SITE_HOME_DIR}:/site/
      - ${NGINX_LOGS}:/var/log/nginx/
    links:
      - php

  php:
    image: l9xhub/php7-fpm:latest
    volumes:
      - ${SITE_HOME_DIR}:/site/
    links:
      - db

  db:
    image: l9xhub/mariadb10.7:latest
    volumes:
      - ${MYSQL_LOGS}:/var/log/mysql/
      - ${MYSQL_CONFS}:/etc/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
