apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
spec:
  selector:
    matchLabels:
      run: mariadb
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        run: mariadb
    spec:
      containers:
      - name: mariadb
        image: my-registry.pp.ua:8483/wordpress/mariadb10.7:latest
        ports:
          - containerPort: 3306
            name: db-port
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wp-mariadb-secret
                key: password
      imagePullSecrets:
      - name: private-registry-cred
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    run: mariadb
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    run: mariadb

