apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
  labels:
    app: php-app
spec:
  selector:
    matchLabels:
      run: php
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        run: php
    spec:
      containers:
      - name: php
        image: l9xhub/php-fpm:latest
        volumeMounts:
        - mountPath: "/site"
          name: hostpath-privileged

        ports:
        - containerPort: 9000
          name: php-port
      volumes:
      - name: hostpath-privileged
        persistentVolumeClaim:
          claimName: wp-pv-volume

      imagePullSecrets:
      - name: private-registry-cred
---
apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    run: php
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 30002

  selector:
    run: php
